"use client";

import { cn } from "@/lib/utils";
import type { GenerationSource } from "@/lib/visualisations/types";

const STYLES: Record<GenerationSource, { label: string; className: string; title: string }> = {
  ai: {
    label: "AI",
    className: "bg-violet-100 text-violet-800 border-violet-200",
    title: "Generated by AI from your project context",
  },
  manual: {
    label: "Edited",
    className: "bg-amber-100 text-amber-800 border-amber-200",
    title: "Manually edited on the canvas",
  },
  template_fallback: {
    label: "Template",
    className: "bg-slate-100 text-slate-700 border-slate-200",
    title: "Deterministic template (no OpenAI API key, or AI response was invalid)",
  },
};

export function SourceBadge({ source }: { source: GenerationSource | undefined }) {
  if (!source) return null;
  // "template" (no API key path) and "template_fallback" (AI failed) are
  // visually the same — both indicate the deterministic template.
  const key = source === "manual" || source === "ai" ? source : "template_fallback";
  const s = STYLES[key];
  return (
    <span
      title={s.title}
      className={cn(
        "inline-flex items-center text-[10px] font-bold uppercase tracking-wider px-1.5 py-0.5 rounded border",
        s.className,
      )}
    >
      {s.label}
    </span>
  );
}
